image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - test
  - deploy
  
variables:
  project: "DevOpsAssessment"

build:
  stage: build
  script:
    
    - "dotnet build ./DevOpsAssessment/DevOpsAssessment.sln"

test:
  stage: test
  script:
 
    - "dotnet test ./DevOpsAssessment/DevOpsAssessment.sln"
